### ISSUE TITLE
Upgrade to bootstrap-notify

### ISSUE THREAD

**Issue by jbbr** [zimme/meteor-bootstrap-growl#2]
It would be great to have this package upgraded to 3.0.x. This is as easy as updating the submodule because the api hasn't changed much.

Also the name has been changed from bootstrap-growl to bootstrap-notify - maybe this wrapper should be renamed too.

**Comment by zimme** [comment]
I'm planning to create a PR for the original package to add meteor packaging directly using the autopublish.meteor.com to automate the publishing process. BUT I haven't had the time to do so yet..

If I can carve out some time tonight I might be able to just update this package to the newer version for the time being.

**Comment by zimme** [comment]
PR has been sent. When the author merges it, I will deprecate this package in favor of his.

Follow the PR here: [#85](https://github.com/mouse0270/bootstrap-notify/pull/85)

**Comment by zimme** [comment]
[`mouse0270:bootstrap-notify`](https://atmospherejs.com/mouse0270/bootstrap-notify) has landed. Deprecating this package in favor of that one.
